### ISSUE TITLE
Feature request: Comms radio

### ISSUE THREAD

**Issue by AndersHogqvist** [mracko/MSFS-Mobile-Companion-App#2]
One of my biggest concerns when flying with live ATC (VATSIM) is the constant changing of comms radio frequency. Having the possibility to set that in this app would make life sooooo much easier! Preferably by just writing the frequency directly.

**Comment by Thaiger52** [comment]
This and the possibility to put waypoints on the map showing distance and heading for the resp. segments would make this app complete.....

**Comment by mracko** [comment]
@AndersHogqvist: COMs will be implemented for sure. They will work similarly to NAVs. Since I don't fly with live ATC and never manually adjust COM frequecies, is there any additional button that's needed for COM frequencies?

@Thaiger52: I like the idea and will keep in the backlog. But first I want to add COMs, some instruments like lights and deicing, and a GPS track on map.

**Comment by AndersHogqvist** [comment]
@mracko Nice to hear!
I actually checked out your code and started to implement this myself, but I'm afraid my HTML/JS/Python skills have faded away over the years. I was thinking something like this:

- Support for comm 1 and 2 (some aircraft have three radios but I'm not sure that's even supported by the sim?)
- The active frequency should be displayed but not editable
- The standby frequency should be editable with an input field
- A "set" button for the standby frequency. In the callback for this button the value should be checked so that it's valid (freq >= 13.975 && freq <= 118.000 && freq % 0.025 == 0)
- For each radio there should be a button that switch the standby frequency and active frequency (standby -> active and active -> standby)

Bonus features:
- For each radio there should be toggle button to turn on/off monitoring
- Radio buttons to switch between active radio (which one you transmit on)

**Comment by mracko** [comment]
Thanks for the info! I'm working on it so no need to do anything. I'll use the NAV page as a template for it. I don't think COM3 is supported. I haven't seen it in the SDK documentation so, I'll stick with the 2.

I would also like add the  transpoder. I would model it after the ADF. One question regarding this: do you know if there is a range for trnaspoder codes? Or is it 0000 to 9999? And do you know if there is a set/enter tranponder code button or is just adjusting the code and the transponder automatically uses it?

**Comment by AndersHogqvist** [comment]
I don't think there are any limitations for the code. As for the other question it differs between aircraft. In the TBM930 with the G3000 you enter the code and then hit "Enter" to execute but in the A320 there are no such button, you just enter the code and then it's active. I would suggest having a "set" button in your app for consistency.

**Comment by Thaiger52** [comment]
> Thanks for the info! I'm working on it so no need to do anything. I'll use the NAV page as a template for it. I don't think COM3 is supported. I haven't seen it in the SDK documentation so, I'll stick with the 2.
> 
> I would also like add the transpoder. I would model it after the ADF. One question regarding this: do you know if there is a range for trnaspoder codes? Or is it 0000 to 9999? And do you know if there is a set/enter tranponder code button or is just adjusting the code and the transponder automatically uses it?

Transponder Code Range is 0000 - 7777 !!!

**Comment by Thaiger52** [comment]
Or more precise: no 8 or 9,

**Comment by AndersHogqvist** [comment]
Yes you are absolutely right, my bad. Its octal, not decimal. 

@mracko About the comms radio, please make sure the frequencies have 3 decimals. I tried FsRadioPanel yesterday, a very similar app but with 2 decimals in the frequencies rendering it completely unusable for this purpose. And I had to dial the frequency rather than just enter it, so even though that app may have a fancier UI your app is more practical and useful!

**Comment by mracko** [comment]
@Thaiger52: Thanks! Implemented.

@AndersHogqvist: I have already a working COM with 3 decimals and a transponder. I'm now dealing with a little JavaScript bug for the frequency swap. The code simply switches the values in variables for the active and standby frequency using one dummy variable. Nothing out of the ordinary, pretty simple. However, when I repeatedly and quickly press the buttons the vars mess up (or the jQuery that displays the var). I'm investigating.

Regarding frequencies: I've noticed that in MSFS on G1000 and G530 panels you can't tune into XXX.X95, XXX.X70, XXX.X45, XXX.X20 MHz frequencies. Is that a bug or is it how it should be?

**Comment by AndersHogqvist** [comment]
The comm frequency should be increments of 25 kHz (0.025MHz), so frequency % 0.025 should be 0. 117.095 is not a valid frequency as far as I can tell.

**Comment by AndersHogqvist** [comment]
Regarding the problems you have with fast swapping of frequencies, are you communicating with the sim asynchronously? To me this sounds like a classic race condition that is very typical for asynchronous operations. I'm not sure how you deal with that in JS/JQuery but there should be plenty of solutions out there.

**Comment by mracko** [comment]
Actually, in the case of NAV and COM frequencies, the javascript doesn't communicate with the sim except at launch. The reason for this is that you have a 1 to 2 second delay when reading data from the sim. You don't have this delay when pushing commands to the sim btw. 

The way I solved this (current Python SimConnect) limitation, is to load up the frequencies only at start. Eg when you swap a frequency, the app pushes the event to the sim and swaps the vars independently of the sim (internally in JS).

So you have:
dummy = nav1
nav1 = nav2
nav2 = dummy
JQuery to display vars

It works perfectly when you do it slowly. But the moment you start tapping the button quickly, the vars mess up. Again, this swap is done independently of the sim. I could introduce the same wait popup I use for the AP buttons, but I'd like to fix it properly.

**Comment by AndersHogqvist** [comment]
I'm still quite sure this is a case of race condition. You are using global variables, in my experience something you should avoid in an event based application regardless of language. If I were you I would get rid of those and get the values directly from the input elements wherever they are needed. I would give this a try:

function nav1switch() {
  var active = $("#nav1_active").val();
  var stdby  = $("#nav1_standby").val();
	$("#nav1_active").text(stdby.toFixed(2));
	$("#nav1_standby").text(active.toFixed(2));
}

Also, I would suggest using one event handler for each button and set it in the script rather than having an onclick with multiple function calls. It makes the code cleaner having all the code in the script and it's easier to maintain.

**Comment by mracko** [comment]
Thanks a lot for the tip. I'll give it a try and let you know.

Just so that you know. I started coding such apps fairly recently and don't consider myself a pro. It's learning while doing and having fun on something useful. I know what I want to achieve so I try to find ways how to get there. One step at a time and hopefully we'll have a solid mobile companion app for MSFS. So if you have any suggestions (optimization, code clean-up, whatever), then please let me know.

Right now I'm concentrating on two things. Finishing COMs and making the app multithreaded (one thread for SimConnect and one for Flask). I think multithreading is a solution for performance and stability issues.

**Comment by AndersHogqvist** [comment]
I used to do some web and app stuff some years ago but I'm no pro either, but who said you need to be? 🙂 That's the power of the open source community, you don't need to be an expert to make something awesome since it's a team effort.

For the past three years I'm a system engineer working with simulators and we code in C/C++, so I'm not up to speed on JQuery etc. However, I've had my share of multi-threading headaches and it can by quite tricky regardless of what type of language you use.

I don't know if you're familiar with the concept of race conditions, but if not I strongly suggest reading up on it since it can cause a lot of bugs that's super hard to pinpoint.
