### ISSUE TITLE
Where the heck is the IOS app

### ISSUE THREAD

**Issue by n9533** [mracko/MSFS-Mobile-Companion-App#22]
Hey guys!

Really looking forward to trying MSFS MCA however I was looking on the app store on my iPhone and couldn't;t find the app. Where is it, and what is it called?

**Comment by Revel8804** [comment]
There is not a mobile app. When you first launch the program. You will get a screen that looks similar to this.
![image](https://user-images.githubusercontent.com/66074617/104627696-fb6aea00-565c-11eb-864f-3f7dd538a94a.png)
On your phone or any device really. Open your browser (Safari, Edge, Chrome, Firefox, whatever) and enter the IP and port in the black box.

So for example on my machine i would enter 
http://192.168.1.100:4000

Creating it this way makes it so pretty much any device can access it. You can also open it on multiple machines.
I regularly have it running on my iPad and computer.

**Comment by mracko** [comment]
Thanks @Revel8804 for clarifying how this app works.
