### ISSUE TITLE
Trim slider controls?

### ISSUE THREAD

**Issue by EdwardTX2** [mracko/MSFS-Mobile-Companion-App#30]
Just installed this tonight. -- awesome!!
Any chance of adding slider controls for elevator and aileron trim?

**Comment by mracko** [comment]
Thanks for the feedback! The problem with trim slider controls is to make them work good with a 1,5 seconds latency for data coming from the sim to the app. For most features like AP or light controls, this isn't a problem. For frequency tuning, I have a workaround. For trim controls, I haven't yet found a way to make a reasonable solution. But I'm not giving up. :)

**Comment by mracko** [comment]
Feature has been implemented. I'm closing this issue.
