### ISSUE TITLE
App Crashing - Unknown Circumstances

### ISSUE THREAD

**Issue by cprgolds** [mracko/MSFS-Mobile-Companion-App#4]
I have been testing the program out with a C172.
I get it to run for a while, and then I get the following error (repetitively):

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "SimConnect\SimConnect.py", line 173, in _run
  File "_ctypes/callproc.c", line 948, in GetResult
OSError: [WinError -1073741648] Windows Error 0xc00000b0

I don't know if this is operator error on my part or a problem with the program.  I am also wondering if there might be a conflict on Port 4000.

I saw some discussion of a similar issue here:

https://github.com/hankhank10/MSFS2020-cockpit-companion/issues/3

**Comment by cprgolds** [comment]
Update:

I did more testing and used an iPad instead of my laptop as the client.  No crashes.

Only issue I saw was that the map kept vacillating between the location I was (Washington State, USA) and what appeared to be France (from the names).

Wil keep you posted.

**Comment by mracko** [comment]
I've been testing the asyncio branch of the original Python SimConnect library https://github.com/odwdinc/Python-SimConnect/tree/asyncio-test. The results look good so far. I'll post the implementation to the Mobile Companion App this weekend. Hopefully, it will resolve the OSError.

I'll check issue with the map switching between your current location and the default one. I haven't encoutered this problem so far, but I'll check the code and see if I can improve it somehow.

Thanks!

**Comment by mracko** [comment]
@cprgolds, I've created a branch with v1.2 that will hopefully fix your issue:

https://github.com/mracko/MSFS-Mobile-Companion-App/tree/MCA-v1-2-COMs-Multithreading

Please, check it out and let me know if it fixed your issue. Thanks.
