### ISSUE TITLE
Latest update broke the FP connector!

### ISSUE THREAD

**Issue by tjugpal** [mracko/MSFS-Mobile-Companion-App#43]
Latest update causing CTD on startup. Only for the Flightplan connector in the community folder. The rest is working!

**Comment by mracko** [comment]
Thanks for the notice! I've updated MSFS and I can confirm that the new update causes a CTD together with the WASM module in the community folder.

(Un)fortunately, all standalone WASM modules (SPAD.neXt, AaO, etc) are affected by this at the moment. I will keep a close eye on this issue and let you know as soon as I know more.

In the meantime, I suggest removing the WASM module from your community folder. The app will run fine except for some buttons (esp. GPS and 3rd party aircraft).

**Comment by mracko** [comment]
Bug has been fixed with MSFS version 1.15.8.0
