### ISSUE TITLE
Feature Request: Change units on Aviation Map

### ISSUE THREAD

**Issue by EdLadner** [mracko/MSFS-Mobile-Companion-App#44]
Currently default units on the Aviation map for airports is in metric, with the airport altitude being shown in meters above MSL.  Ground feature elevations (in topo) show altitude in feet.  
Can this be made switchable depending upon the aircraft to show in feet or meters for both?

**Comment by mracko** [comment]
I'll have a look into it, but I'm not sure whether it can be changed in the map.

**Comment by mracko** [comment]
Unfortunately, I can't change this because I'm relying on existing open-source maps. I'll close this issue for now as I don't see a solution anytime soon.
