### ISSUE TITLE
Gear Lever position

### ISSUE THREAD

**Issue by e4rthdog** [mracko/MSFS-Mobile-Companion-App#45]
I ant find a gear lever position.

It's easily doable by adding just:
`ui_friendly_dictionary["GEAR_HANDLE_POSITION"] = await aq.get("GEAR_HANDLE_POSITION")`

Should i create a fork and make a request or you are adding it?

**Comment by mracko** [comment]
Thanks for the contribution! I will be releasing an update hopefully next week that will include a separate tab for gear, flaps, spoilers and trim (elevator, rudder, aileron).
