### ISSUE TITLE
Bug when using on mobile

### ISSUE THREAD

**Issue by mpirescarvalho** [mracko/MSFS-Mobile-Companion-App#52]
The site doesn't work at all on my smartphone: the website opens but I press the panel buttons and nothing happens. The map stays open, but the airplane position is wrong and freezed.

It works perfectly when opening on PC though.

I've tried:
- Disabling windows defender
- Disabling firewall
- Setting network to private

If it helps:
- I've just downloaded last release. 
- I'm using android.
- The pc is connected to the network with a cable.
- The smartphone is connected to the network with wi-fi.

**Comment by cprgolds** [comment]
Hi Marcello -- I had a lot of trouble with the interactions of Windows Defender and the Norton Firewall, but finally solved them.

When you say that MCA is "working on PC", is this the same PC that MSFS is running o, or is it a different PC on the network?

What firewall are you using?

Here is what was happening in my case:  My firewall was blocking MCA.  I suspected that and turned off the firewall, and MCA was still blocked.  What was happening is that when I turned off the firewall, Windows Defender automatically turned on its firewall.

I ended up adding a firewall rule for MCA and it works fine in v1.7 and v1.8-1.

I haven't tried it with Android, just PCs and an iPad.  Its late here.  I'll watch this tomorrow, and, if needed, can try it on my android phone.

**Comment by mracko** [comment]
Hi Marcelo!
What you're describing looks like a JavaScript issue on your Android device. It's doesn't look like a connection issue because otherwise you wouldn't see the MCA website. I've heard similar reports on older iPads but you're the first using an Android.
What kind of device and Android version are you using?

Alternatively, I could be that you start the MCA EXE before the sim is properly loaded. Make sure you're in the main menu of MSFS before launching the client.

Hope this helps!

**Comment by cprgolds** [comment]
Hey Guys - I tried it on my Pixel 5 with latest Android 11 and everything appears to work fine.

**Comment by mpirescarvalho** [comment]
> When you say that MCA is "working on PC", is this the same PC that MSFS is running o, or is it a different PC on the network?

Yes, it is the same PC that MSFS and MCA is running, I don't have another PC to test it.

> What firewall are you using?

I'm using the default firewall that comes with windows 10. I have tried disabling it all (windows defender and firewall) but it didn't work either.

**Comment by mpirescarvalho** [comment]
@mracko Yeah, it's weird that I can see MCA website but can't interact with it, but every other website it's working fine 🤔

I have also downloaded another browser (opera) but it also didn't work.

I'm on XIAOMI with 12.0.7 MIUI version and android 10

**Comment by cprgolds** [comment]
@mpirescarvalho - Do you have another device that you can try MCA on.  I am still thinking that there is a firewall issue and if another device does the same thing, this would narrow down the possibilities.

It may be the difference in how the firewall is handling inbound and outbound traffic.

**Comment by mpirescarvalho** [comment]
Yep, tried on another smartphone and it worked. Any idea of what could it be?

**Comment by cprgolds** [comment]
@mpirescarvalho - Well that should rule out your PC firewall and router.

This looks like a similar situation with 12.0.7 MIUI.  https://community.spotify.com/t5/Android/Spotify-freezes-on-startup-and-doesn-t-respond/m-p/5194526

Was the smartphone that it worked on another Xiamoi??

**Comment by mpirescarvalho** [comment]
Yes, it was the REDMI NOTE 8. I don't know about the MIUI version but I believe it's 12 as well.

PS.: I'm also a dev and I'm pretty sure I've used the port 4000 before, may it be a cache issue? I'll try cleaning it

**Comment by mpirescarvalho** [comment]
Had no success 😕

**Comment by bushnerd** [comment]
> Hi Marcelo! What you're describing looks like a JavaScript issue on your Android device. It's doesn't look like a connection issue because otherwise you wouldn't see the MCA website. I've heard similar reports on older iPads but you're the first using an Android. What kind of device and Android version are you using?
> 
> Alternatively, I could be that you start the MCA EXE before the sim is properly loaded. Make sure you're in the main menu of MSFS before launching the client.
> 
> Hope this helps!

I also have this problem. I tried firefox lates version. It does not work.
I think it should be javascript issue not firewall, because i close firewall and other apps such as flightdisplaycompnion works well.

And i try to access some websites,
twitter,youtube not work
google and baidu works, but if i tap some links which may needs some resouce, it does not work.
