### ISSUE TITLE
Request: Option to turn of plane position on map for VFR only flight

### ISSUE THREAD

**Issue by xxTheGoDxx** [mracko/MSFS-Mobile-Companion-App#56]
I personally have more fun in the sim just trying to navigate via the map (with way points) and heading indicator only, would it be possibly to have the option to disable the GPS position completely on the map?

**Comment by mracko** [comment]
Thanks for the tip. This has already been raised by a different user. I'll try to implement this feature in the upcoming updates. I can't give you an ETA though as I'm developing this in my free time.

**Comment by mracko** [comment]
I've implemented this feature and it will be available in the upcoming v1.9. You will be able to turn off the plane icon by clicking twice on the lower left button on the map. The button has 3 states:
1. Follow plane
2. Unfollow plane
3. Hide plane

Thanks for the tip!
