### ISSUE TITLE
Not able to make custom LVars work.

### ISSUE THREAD

**Issue by uujfwmnp** [mracko/MSFS-Mobile-Companion-App#60]
I forked MCA with plans to get the Just Flight Piper Warrior to work natively. I've managed to get it 80% going by taking advantage of the native LVars, but it seems that anything that needs a user defined LVar, for example `MobiFlight.JF_WARRIOR_KX175_COMM2_OUTER_KNOB_PLUS` doesn't work. I noticed in the release version of MCA there's a file/folder structure "mobiflight-event-module/modules/StandaloneModule.wasm" that is missing. Would this be something I might need to copy into my local build?

Thanks!

**Comment by mracko** [comment]
That's correct. LVars can't be accessed via standard SimConnect but need the MobiFlight WASM module that I've included in the release ZIP file. In this repo you'll only find the custom LVar commands which need to be created for the 3rd party planes. This file is located here: 
https://github.com/mracko/MSFS-Mobile-Companion-App/blob/master/MobiFlight%20Custom%20Events/events.user.txt

I haven't looked into the Warrior yet, but I assume that it will need similar commands as the Arrow.

**Comment by uujfwmnp** [comment]
Excellent, I'll copy the mobiflight folder over and keep plugging away. I'll push and PR the branch to you once I get the Warrior all squared away.

**Comment by mracko** [comment]
Thanks! Perfect! Let me know if you need any assistance.
