### ISSUE TITLE
Can't set FLC autopilot mode

### ISSUE THREAD

**Issue by rsparkyc** [mracko/MSFS-Mobile-Companion-App#7]
Maybe I'm blind, but I didn't see an option to set FLC mode. I use this alot during ascent.

**Comment by mracko** [comment]
It's true that FLC mode isn't implemented. I'll need to test it first and then I'll add it in the next version. What plane would you recommend to test FLC mode?

Thanks for the input!

**Comment by mracko** [comment]
I've just implemented the FLC mode. Please have a look at it and let me know what you think of it.

**Comment by mracko** [comment]
FLC implemented in v1.3
