### ISSUE TITLE
Stadia Maps

### ISSUE THREAD

**Issue by Revel8804** [mracko/MSFS-Mobile-Companion-App#8]
Is the connection to Stadia Maps broken? Or is it just me?

Looks like I am getting a 403 error to it now.

**Comment by mracko** [comment]
I've also had trouble loading the dark theme yesterday. I'll investigate the issue. Please let me know if this problem persists or if it works again.

Thanks

**Comment by Revel8804** [comment]
Stadia is still not working for me on 1.4
It has not worked since the first time i reported this

**Comment by mracko** [comment]
Unfortunately, I can't really reproduce the issue. While looking at the issue I've noticed that an API is actually required. I'll contact the provider and see what can be done about this. Worst case, I'll drop Stadia and use OSM instead.

**Comment by mracko** [comment]
I've contacted the Stadia maps dev and he said that there are actually hard caps on localhost traffic (which is what we use) to ensure it isn't abused. Can it be that your IP is somehow hitting a limit.

Nevertheless, the dev was very kind and suggested we switch to vector tiles instead of the current raster tiles. I'm looking into ways of implementing it.

**Comment by Revel8804** [comment]
ha probably. I might play a lot........
Do you know if there is a way to determine if that is what is happening? Other than the forbidden error?
I might just have to always use openstreet.

**Comment by mracko** [comment]
Maybe you do! :) He didn't mention anything specific so it's hard to tell. I'll try to implement the vector tiles so let's see.

**Comment by Revel8804** [comment]
I love the new landscape mode! It is now my default mode.

Ya Stadia maps is still not working for me. No clue why. Since I seem to be the only one with this issue, I will go ahead and close the issue.
