### ISSUE TITLE
Feature request: Toggle monitoring of comms 1/2

### ISSUE THREAD

**Issue by AndersHogqvist** [mracko/MSFS-Mobile-Companion-App#9]
The addition of comms was really nice, but it would be even nicer if you could add  monitoring and transmitt  toggle buttons for each radio.

**Comment by mracko** [comment]
Thanks for the tip. I've included the COM 1 and COM 2 transmit toggle. Since I don't actively use COMs, could you please elaborate more on how it should the two features should work.

**Comment by AndersHogqvist** [comment]
It's a simple toggle for each radio. When it's on you listen on that radio, when off you don't 🙂

**Comment by mracko** [comment]
I've just checked the documentation. It seems that for the time being I will not be able to implement monitoring/listening functionalities apart from the two buttons that are currently available. If you, however, know which SimConnect events are relevant, then please let me know. I may have missed something in the SDK documentation.

**Comment by AndersHogqvist** [comment]
Oh, that's unfortunate. Hopefully they will add those in the future.
